### ISSUE TITLE
Enhancement 1: Add Products in detail table

### ISSUE THREAD

**Issue by mortoza** [mstahv/jpa-invoicer#10]
Hi
As you encouraged me to contribute to this example application by providing inputs in one of your response. I am looking at adding products in the detail table of the invoice.

I gave a try but something is wrong somewhere. Here is what I did:
1) Added an Entity (table name: Product) with fields Id, Name
2) Added the following field in InvoiceRow entity

```
@NotNull
@JoinColumn(name = "Product_Id", referencedColumnName = "ID")
@ManyToOne
private Product products;
```

3) Updated  InvoiceForm and looks like below

@ViewScoped
public class InvoiceForm extends AbstractForm<Invoice> {

```
@Inject
ContactSelector to;

@Inject
ProductFacade facade;
ComboBox productCombo;

DateField invoiceDate = new DateField("invoiceDate");

DateField dueDate = new DateField("dueDate");

Header total = new Header("").setHeaderLevel(3);

public static final class RowEditorModel {
    MTextField products = new MTextField().withFullWidth();
    MTextField description = new MTextField().withFullWidth();
    MTextField amount = new MTextField().withWidth("200px");
    MTextField unit = new MTextField().withWidth("3em");
    MTextField price = new MTextField().withWidth("3em");
}

ElementCollectionTable<InvoiceRow> invoiceRows = new ElementCollectionTable<>(
        InvoiceRow.class, RowEditorModel.class);

@PostConstruct
void init() {
    productCombo=new ComboBox();

    // Allowing null in DB, but not when modified by the UI
    to.setRequired(true);
    to.addValidator(new AbstractValidator("Receiver must be set") {

        @Override
        protected boolean isValidValue(Object value) {
            return value != null;
        }

        @Override
        public Class getType() {
            return Contact.class;
        }
    });

    invoiceRows.addValueChangeListener(e -> updateTotal());


}

@Override
protected Component createContent() {
```

tableCombo();
        return new MVerticalLayout(
                new MHorizontalLayout(getToolbar()).add(total,
                        Alignment.MIDDLE_RIGHT)
                .withFullWidth(),
                new MVerticalLayout(
                        to,
                        new MHorizontalLayout(invoiceDate, dueDate),
                        invoiceRows
                )
        );

```
}

void updateTotal() {
    try {
        total.setText(getEntity().getTotal() + " €");
    } catch (Exception e) {
        total.setText("--");
    }
}

@Override
public Window openInModalPopup() {
    final Window p = super.openInModalPopup();
    p.setWidth("80%");
    p.setHeight("95%");
    return p;
}


private void tableCombo() {
    invoiceRows.getTable().setTableFieldFactory(new DefaultFieldFactory() {
        @Override
        public Field createField(Container container, Object itemId,
                Object propertyId, Component uiContext) {
            if ("products".equals(propertyId)) {
                List<Product> prodList = facade.findAll();
                BeanItemContainer<Product> prodContainer = new BeanItemContainer<>(Product.class, prodList);
                //productCombo = new ComboBox();
                productCombo.setContainerDataSource(prodContainer);
                return productCombo;
            }
            return super.createField(container, itemId, propertyId, uiContext);
        }
    });
}
```

}

4) I am getting exception :+1: Caused by: java.lang.NullPointerException
    at org.example.InvoiceForm.tableCombo(InvoiceForm.java:120)
    at org.example.InvoiceForm.init(InvoiceForm.java:83)
    ... 91 more

Warning:   Error in serialization of the application: Class in.virit.WidgetSet$1$1 must implement serialization.
Info:   Cannot serialize session attribute com.vaadin.server.VaadinSession.VaadinServlet for session dc465c717e61f0fe700f1a6d0cf1
java.io.NotSerializableException: in.virit.WidgetSet
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)

**Comment by mstahv** [comment]
Check out the current implementation or a change before it (there was a relation from InvoiceRow to Product, but I decided to remove it finally). With the ElementCollectionTable things should work in the same way.

I fixed the [missing serialisable interface](https://github.com/viritin/vwscdn/commit/ef251b87a62d64dca512548c3779162feedc8867) in the Viritin CDN a moment ago, will be fixed in next release. Thanks noticing this.
