### ISSUE TITLE
Automatic insertion of row in ElementCollectionTable

### ISSUE THREAD

**Issue by mortoza** [mstahv/jpa-invoicer#11]
Hi
When we use ElementCollectionField, a new row is automatically inserted in the end when the last row is edited. I like this. How can I turn this option on when I am using ElementCollectionTable  where i'll not need to click + button.

regards
Mortoza

**Comment by mstahv** [comment]
Hi, would you open this issue to [viritin](https://github.com/viritin/viritin) project instead ?
