### ISSUE TITLE
How to run jpa-invoicer

### ISSUE THREAD

**Issue by tgarijo** [mstahv/jpa-invoicer#21]
Hi, I have a question..

How to run jpa-invoicer.

I run "mvn install" works perfect
I run "mvn jetty:run" doesn't work

**Comment by alejandro-du** [comment]
Hi, can you post the error message/log?

**Comment by tgarijo** [comment]
[INFO] Scanning for projects...
[INFO] Downloading: http://virit.in/maven2/org/apache/maven/plugins/maven-metadata.xml
[INFO] Downloading: http://virit.in/maven2/org/codehaus/mojo/maven-metadata.xml
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 22.7 KB/sec)
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 34.1 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.393 s
[INFO] Finished at: 2016-04-11T11:04:46+02:00
[INFO] Final Memory: 12M/193M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\tgarijo.m2\repository), viritin (http://virit.in/maven2), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

I add pluging in pom.xml but it I had other error, may be I didn't configure well

**Comment by alejandro-du** [comment]
I've just remembered we are using WildFly in this project. Try `mvn wildfly:run`.

**Comment by tgarijo** [comment]
Ok now works fine. Thank You very much.
Best Regards,
Tomas
