### ISSUE TITLE
Support user defined invoice templates

### ISSUE THREAD

**Issue by mstahv** [mstahv/jpa-invoicer#4]
Invoice template is currently hardcoded. It should be possible for users to upload their own customized template, per invoicer.

**Comment by mortoza** [comment]
Hi 
How about adding option to use jasperreports (iReport) to generate invoice? This will allow change of design later

Mortoza

**Comment by mstahv** [comment]
Hi, do you have some experience of various reporting libraries in Java? I don't have that much, so all insights would be valuable. I chose xdocreports and with it, it should be pretty easy for end user to use normal office apps (LibreOffice, MS Office) as "designers" for the templates. 

So my plan was to just provide user a way to download the default template, modify it and upload it to be used as the template for invoicer.

**Comment by mortoza** [comment]
Hi Matti
I use Jasperreports (iReport) for my java application. As it is open source and pixel perfect reporting library/visual design tool, users will be able to modify as needed. Your idea to maintain a template is great!

Beyond reports question, I have some experience in developing real-life ERP system, I can share with you some ideas to enhance this sample invoice application, let me know if you want to..

**Comment by mstahv** [comment]
Sure, feel free to add new issues for enhancement ideas. I want to keep this example relatively simple but to cover bit more real world usage examples than our naive address book example.
